using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using XoSoKienThiet.BUS;
using System.Data.Entity;
using XoSoKienThiet.DTO;

namespace XoSoKienThiet.Presentation
{
    public partial class frmKetQuaXoSo : DevExpress.XtraEditors.XtraForm
    {
        DOTPHATHANH_BUS _DOTPHATHANH_BUS = null;
        LOAIVE_BUS _LOAIVE_BUS = null;
        public frmKetQuaXoSo()
        {
            InitializeComponent();
            _DOTPHATHANH_BUS = new DOTPHATHANH_BUS();
            _LOAIVE_BUS = new LOAIVE_BUS();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            XoSoKienThiet.DTO.XoSoKienThietDbContext dbContext = new XoSoKienThiet.DTO.XoSoKienThietDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.CT_KETQUAXOSO_VIEW.Load();
            // This line of code is generated by Data Source Configuration Wizard
            bindingSource1.DataSource = dbContext.CT_KETQUAXOSO_VIEW.Local.ToBindingList();
        }

        private void frmKetQuaXoSo_Load(object sender, EventArgs e)
        {
            #region #Lookup đợt phát hành
            var ListDotPhatHanh = _DOTPHATHANH_BUS.Select_Con_Company("DT00000001");
            lkDotPhatHanh.Properties.DataSource = ListDotPhatHanh;
            lkDotPhatHanh.Properties.DisplayMember = "MaDotPhatHanh";
            lkDotPhatHanh.Properties.ValueMember = "MaDotPhatHanh";

            lkDotPhatHanh.Properties.ForceInitialize();
            lkDotPhatHanh.Properties.PopulateColumns();

            lkDotPhatHanh.Properties.Columns["MaCongTy"].Visible = false;
            #endregion

            //Sel_YourCompany
            #region #Lookup loại vé
            var ListLoaiVe = _LOAIVE_BUS.SelectYourCompany();
            lkLoaiVe.Properties.DataSource = ListLoaiVe;
            lkLoaiVe.Properties.DisplayMember = "MenhGia";
            lkLoaiVe.Properties.ValueMember = "MaLoaiVe";

            lkLoaiVe.Properties.ForceInitialize();
            lkLoaiVe.Properties.PopulateColumns();

            lkLoaiVe.Properties.Columns["MaCongty"].Visible = false;
            #endregion
        }

        private void lkDotPhatHanh_EditValueChanged(object sender, EventArgs e)
        {
            txtNgayXoSo.Text = string.Format("{0:dd/MM/yyyy}", Convert.ToDateTime(lkDotPhatHanh.Properties.GetDataSourceValue("NgayXoSo", lkDotPhatHanh.ItemIndex)));

            XoSoKienThiet.DTO.XoSoKienThietDbContext dbContext = new XoSoKienThiet.DTO.XoSoKienThietDbContext();
            string MaDotPhatHanh = lkDotPhatHanh.Properties.GetDataSourceValue("MaDotPhatHanh", lkDotPhatHanh.ItemIndex).ToString();
            string MaLoaiVe = lkLoaiVe.Properties.GetDataSourceValue("MaLoaiVe", lkLoaiVe.ItemIndex).ToString();
            // Lấy danh sách chi tiết kết quả xổ số như trên , thực ra là đổ giải thưởng lên chi tiết kết quả xổ số
            var List_GiaiThuong = from p in dbContext.GIAITHUONGs
                               where p.MaLoaiVe == MaLoaiVe
                               select p;
            

            List<CT_KETQUAXOSO_VIEW> List_CT_KetQuaXoSo = new List<CT_KETQUAXOSO_VIEW>();
            #region #Hiển thị dữ liệu lên gridview
            foreach (var item in List_GiaiThuong)
            {
                //Gán những thuộc tính có sẵn
                CT_KETQUAXOSO_VIEW ct_ketquaxoso = new CT_KETQUAXOSO_VIEW();
                ct_ketquaxoso.Ten = item.Ten;
                ct_ketquaxoso.SoTienTrung = item.SoTienTrung;
                ct_ketquaxoso.SoGiai = item.SoGiai;
                List_CT_KetQuaXoSo.Add(ct_ketquaxoso);

                // Tính thành tiền và số lượng nhận
                
            }
            //gcBASE.DataSource = List_CT_PhieuNhanVe;
            #endregion
        }
    }
}