using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using XoSoKienThiet.BUS;
using System.Data.Entity;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Columns;
using XoSoKienThiet.DTO;

namespace XoSoKienThiet.Presentation
{
    public partial class frmPhieuNhanVe : DevExpress.XtraEditors.XtraForm
    {

        NHANVIEN_BUS _NHANVIEN_BUS = null;
        CT_PHIEUDANGKYVE_BUS _CT_PHIEUDANGKYVE_BUS = null;
        DOITAC_BUS _DOITAC_BUS = null;
        CT_PHIEUNHANVE_BUS _CT_PHIEUNHANVE_BUS = null;
        LOAIVE_BUS _LOAIVE_BUS = null;
        public frmPhieuNhanVe()
        {
            InitializeComponent();
            _NHANVIEN_BUS = new NHANVIEN_BUS();
            _CT_PHIEUDANGKYVE_BUS = new CT_PHIEUDANGKYVE_BUS();
            _DOITAC_BUS = new DOITAC_BUS();
            _CT_PHIEUNHANVE_BUS = new CT_PHIEUNHANVE_BUS();
            _LOAIVE_BUS = new LOAIVE_BUS();
            #region #Hiển thị txtTenDoiTac theo MaPhieuDangKy
            XoSoKienThiet.DTO.XoSoKienThietDbContext dbContext = new XoSoKienThiet.DTO.XoSoKienThietDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.PHIEUDANGKYVE_DOITAC_VIEWs.Load();
            // This line of code is generated by Data Source Configuration Wizard
            bindingMaPhieuDangKy.DataSource = dbContext.PHIEUDANGKYVE_DOITAC_VIEWs.Local.ToBindingList();
            #endregion
        }

        private void frmPhieuNhanVe_Load(object sender, EventArgs e)
        {
            #region #Load danh sách nhân viên
            var _ListNhanVien = _NHANVIEN_BUS.Select();
            lkNguoiLap.Properties.DataSource = _ListNhanVien;
            lkNguoiLap.Properties.DisplayMember = "Ten";
            lkNguoiLap.Properties.ValueMember = "MaNhanVien";

            lkNguoiLap.Properties.ForceInitialize();
            lkNguoiLap.Properties.PopulateColumns();

            lkNguoiLap.Properties.Columns["MaCoCauToChuc"].Visible = false;
            lkNguoiLap.Properties.Columns["DiaChi"].Visible = false;
            lkNguoiLap.Properties.Columns["Email"].Visible = false;
            lkNguoiLap.Properties.Columns["SDT"].Visible = false;
            #endregion
        }
        private void lkMaPhieuDangKy_EditValueChanged(object sender, EventArgs e)
        {

            txtTenDoiTac.Text = lkMaPhieuDangKy.Properties.GetDataSourceValue("Ten", lkMaPhieuDangKy.ItemIndex).ToString();
            XoSoKienThiet.DTO.XoSoKienThietDbContext dbContext = new XoSoKienThiet.DTO.XoSoKienThietDbContext();

            string _MaPhieuDangKy = lkMaPhieuDangKy.Properties.GetDataSourceValue("MaPhieuDangKy", lkMaPhieuDangKy.ItemIndex).ToString();
            // Lấy danh sách chi tiết phiếu đăng ký có mã phiếu đăng ký như trên
            var _List_CT_PDKC = from p in dbContext.CT_PHIEUTRAVE_VIEW
                                where p.MaPhieuDangKy == _MaPhieuDangKy
                                select p;
            
            List<CT_PHIEUNHANVE_VIEW> _List_CT_PhieuNhanVe = new List<CT_PHIEUNHANVE_VIEW>();
            foreach (var item in _List_CT_PDKC)
            {
               //Gán những thuộc tính có sẵn
                CT_PHIEUNHANVE_VIEW phieunhanve_view = new CT_PHIEUNHANVE_VIEW();
                phieunhanve_view.MaDoiTac = item.MaDoiTac;
                phieunhanve_view.MaDotPhatHanh = item.MaDotPhatHanh;
                phieunhanve_view.MaLoaiVe = item.MaLoaiVe;
                phieunhanve_view.Ten = item.Ten;
                phieunhanve_view.NgayPhatHanh = item.NgayPhatHanh;
                phieunhanve_view.MenhGia = item.MenhGia;
                _List_CT_PhieuNhanVe.Add(phieunhanve_view);

                // Tính thành tiền và số lượng nhận

                int _SoVeNhan = 0, _MenhGia;
                float _TiLeHoaHong, _ThanhTien = 0;
                if (_DOITAC_BUS.IsYourCompany(item.MaDoiTac) == false)
                {
                    _SoVeNhan = Convert.ToInt32(item.SoVeDangKy * _CT_PHIEUNHANVE_BUS.PercentageAmountofTicketReceive(item.MaDoiTac, item.MaDotPhatHanh, item.MaLoaiVe));
                }
                else
                {
                    _SoVeNhan = Convert.ToInt32(item.SoVeDangKy * _DOITAC_BUS.GetPercentageConsume(lkMaPhieuDangKy.Properties.GetDataSourceValue("MaDoiTac", lkMaPhieuDangKy.ItemIndex).ToString()));
                }
                _TiLeHoaHong = _DOITAC_BUS.GetPercentage(lkMaPhieuDangKy.Properties.GetDataSourceValue("MaDoiTac", lkMaPhieuDangKy.ItemIndex).ToString());
                _MenhGia = _LOAIVE_BUS.GetPrice(item.MaDoiTac, item.MaLoaiVe);
                _ThanhTien = _TiLeHoaHong * _MenhGia * _SoVeNhan;
                phieunhanve_view.SoLuongNhan = _SoVeNhan;
                phieunhanve_view.ThanhTien = _ThanhTien;
            }
            gcBASE.DataSource = _List_CT_PhieuNhanVe;
        }
    }
}
