using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using XoSoKienThiet.BUS;
using System.Data.Entity;
namespace XoSoKienThiet.Presentation
{
    public partial class frmTiepNhanNhanVien : DevExpress.XtraEditors.XtraForm
    {
        BOPHAN_BUS _BOPHAN_BUS = null;
        CHUCVU_BUS _CHUCVU_BUS = null;
        NHANVIEN_BUS _NHANVIEN_BUS = null;
        COCAUTOCHUC_BUS _COCAUTOCHUC_BUS = null;
        string _MaNhanVien;
        XoSoKienThiet.DTO.XoSoKienThietDbContext dbContext = new XoSoKienThiet.DTO.XoSoKienThietDbContext();
        public frmTiepNhanNhanVien()
        {
            InitializeComponent();
            _BOPHAN_BUS = new BOPHAN_BUS();
            _CHUCVU_BUS = new CHUCVU_BUS();
            _COCAUTOCHUC_BUS = new COCAUTOCHUC_BUS();
            _NHANVIEN_BUS = new NHANVIEN_BUS();


            XoSoKienThiet.DTO.XoSoKienThietDbContext dbContext = new XoSoKienThiet.DTO.XoSoKienThietDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.NHANVIEN_VIEW.Load();
            // This line of code is generated by Data Source Configuration Wizard
            bindingSource1.DataSource = dbContext.NHANVIEN_VIEW.Local.ToBindingList();
        }

        private void frmTiepNhanNhanVien_Load(object sender, EventArgs e)
        {
            var ListBoPhan = _BOPHAN_BUS.Select();
            var ListChucVu = _CHUCVU_BUS.Select();

            lkBoPhan.Properties.DataSource = ListBoPhan;
            lkBoPhan.Properties.DisplayMember = "TenBoPhan";

            lkBoPhan.Properties.ForceInitialize();
            lkBoPhan.Properties.PopulateColumns();

            lkBoPhan.Properties.Columns["MaBoPhan"].Visible = false;
            lkBoPhan.Properties.Columns["MaQuanLy"].Visible = false;

            lkChucVu.Properties.DataSource = ListChucVu;
            lkChucVu.Properties.DisplayMember = "TenChucVu";

            lkChucVu.Properties.ForceInitialize();
            lkChucVu.Properties.PopulateColumns();

            lkChucVu.Properties.Columns["MaChucVu"].Visible = false;
        }

        private void btnThem_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            string _MaBoPhan  = lkBoPhan.GetColumnValue("MaBoPhan").ToString();
            string _MaChucVu = lkChucVu.GetColumnValue("MaChucVu").ToString();

            string _MaCoCauToChuc = _COCAUTOCHUC_BUS.GetID(_MaBoPhan, _MaChucVu);
            string _Error = _NHANVIEN_BUS.Insert_Upd(_MaCoCauToChuc, txtTenNhanVien.Text, txtSoDienThoai.Text, txtDiaChi.Text, txtEmail.Text);
            if(_Error == "")
            {
                MessageBox.Show("Thêm nhân viên thành công", "THÔNG BÁO", MessageBoxButtons.OK, MessageBoxIcon.Information);
                bindingSource1.DataSource = dbContext.NHANVIEN_VIEW.Local.ToBindingList();
            }
            else
            {
                MessageBox.Show(_Error, "THÔNG BÁO", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void gvBASE_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            _MaNhanVien = gvBASE.GetRowCellValue(gvBASE.FocusedRowHandle, gvBASE.Columns["MaNhanVien"]).ToString();
            txtTenNhanVien.Text = gvBASE.GetRowCellValue(gvBASE.FocusedRowHandle, gvBASE.Columns["Ten"]).ToString();
            txtSoDienThoai.Text = gvBASE.GetRowCellValue(gvBASE.FocusedRowHandle, gvBASE.Columns["SDT"]).ToString();
            txtEmail.Text = gvBASE.GetRowCellValue(gvBASE.FocusedRowHandle, gvBASE.Columns["Email"]).ToString();
            txtDiaChi.Text = gvBASE.GetRowCellValue(gvBASE.FocusedRowHandle, gvBASE.Columns["DiaChi"]).ToString();
           // _MaBoPhan = gvBASE.GetRowCellValue(gvBASE.FocusedRowHandle, gvBASE.Columns["MaBoPhan"]).ToString();
           // _MaChucVu = gvBASE.GetRowCellValue(gvBASE.FocusedRowHandle, gvBASE.Columns["MaChucVu"]).ToString();
            lkChucVu.Text = gvBASE.GetRowCellValue(gvBASE.FocusedRowHandle, gvBASE.Columns["TenChucVu"]).ToString();
            lkBoPhan.Text = gvBASE.GetRowCellValue(gvBASE.FocusedRowHandle, gvBASE.Columns["TenBoPhan"]).ToString();
        }

        private void btnSua_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            string _MaBoPhan = lkBoPhan.GetColumnValue("MaBoPhan").ToString();
            string _MaChucVu = lkChucVu.GetColumnValue("MaChucVu").ToString();

            string _MaCoCauToChuc = _COCAUTOCHUC_BUS.GetID(_MaBoPhan, _MaChucVu);
            string _Error = _NHANVIEN_BUS.Insert_Upd(_MaCoCauToChuc, txtTenNhanVien.Text, txtSoDienThoai.Text, txtDiaChi.Text, txtEmail.Text, _MaNhanVien);
            if (_Error == "")
            {
                MessageBox.Show("Cập nhật nhân viên thành công", "THÔNG BÁO", MessageBoxButtons.OK, MessageBoxIcon.Information);
                XoSoKienThiet.DTO.XoSoKienThietDbContext dbContext = new XoSoKienThiet.DTO.XoSoKienThietDbContext();
                dbContext.NHANVIEN_VIEW.Load();
                bindingSource1.DataSource = dbContext.NHANVIEN_VIEW.Local.ToBindingList();
            }
            else
            {
                MessageBox.Show(_Error, "THÔNG BÁO", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
           
        }
    }
}